### ISSUE TITLE
`variables` nested member expression bug

### ISSUE THREAD

**Issue by adamjanicki2** [mavoweb/vastly#7]
I had a sneaking suspicion that something was off with the recently merged `variables` function with regards to how it handles member expressions, and looks like I was right. Specifically, expressions like `foo[bar]` don't get parsed correctly due to this line in the function:

```js
const propertyChildren = property.type === "Identifier" ? [] : variables(property);
```

The issue with this approach is that these two expressions: `foo.bar`, `foo[bar]` have _nearly_ identical node structures, except the `computed` property, which is `true` for `foo[bar]` (and generalizes to being true for _any_ member expression that uses square brackets) and `false` for `foo.bar` (and generalizes to false for any member expression that uses dot notation).

The fix is easy; it only requires updating the bad line show above to the following line:

```js
const propertyChildren = computed ? variables(property) : [];
```

The code will successfully explore the property if the member expression uses square brackets (and thus may contain other variables), and will not explore the property if it uses dot notation.

**Comment by LeaVerou** [comment]
> I had a sneaking suspicion that something was off with the recently merged `variables` function with regards to how it handles member expressions, and looks like I was right. Specifically, expressions like `foo[bar]` don't get parsed correctly due to this line in the function:
> 
> ```js
> const propertyChildren = property.type === "Identifier" ? [] : variables(property);
> ```

Btw as a tip, rather than pasting a single line, it's better to *also* link to lines in the source like so: https://github.com/mavoweb/vastly/blob/main/src/variables.js#L29 
You can obtain such a link by clicking on the line number, and you can even do whole ranges.
I had to look up that line in the source, as I have no idea what it did in isolation.

> The issue with this approach is that these two expressions: `foo.bar`, `foo[bar]` have _nearly_ identical node structures, except the `computed` property, which is `true` for `foo[bar]` (and generalizes to being true for _any_ member expression that uses square brackets) and `false` for `foo.bar` (and generalizes to false for any member expression that uses dot notation).

Good catch! I should have caught that in code review.

> The fix is easy; it only requires updating the bad line show above to the following line:
> 
> ```js
> const propertyChildren = computed ? variables(property) : [];
> ```
> 
> The code will successfully explore the property if the member expression uses square brackets (and thus may contain other variables), and will not explore the property if it uses dot notation.

No objection at all, and good research. 👍🏼 
My only advice would be, it's more customary to file the bug as soon as you have enough data about what cases reproduce it, and do the exploration on the cause later or even as part of the PR. Here you've basically outlined the PR in the first post, i.e. you've waited to file the bug until you had also fixed the bug, which may work for small/early projects but in general it doesn't let you get any help and doesn't give anyone else the chance to help.

**Comment by adamjanicki2** [comment]
Got it, noted for future bugs like this!
